#!/usr/bin/env python3
"""Satu sumber kanonik, adapter yang DIHASILKAN — bukan salinan yang menyimpang diam-diam.

    python3 tools/adapters.py            # tulis ulang adapters/ dari skills/samewrite/SKILL.md
    python3 tools/adapters.py --check    # exit 1 bila adapters/ tak sama dengan hasil generate

Kanonik = skills/samewrite/SKILL.md (Claude Code memuatnya langsung). Adapter hanya mengganti
metadata di kepala; badannya byte-identik. Host lain membaca berkas Markdown instruksi
(Codex/OpenCode: AGENTS.md; Gemini CLI: GEMINI.md) — dukungan di sana INSTRUCTION_ONLY,
belum diuji perilakunya (docs/VNEXT.md §matriks dukungan).

Hermes Agent memuat berkas SKILL.md gaya Claude Code APA ADANYA (diverifikasi, lihat
experiments/hermes/), dengan SATU perbedaan yang mengikat: deskripsi dipotong jadi 60 karakter
di prompt sistemnya. Deskripsi kanonik kita 391 karakter, jadi memakai berkas kanonik langsung
akan membuang 331 karakter informasi perutean tepat di tempat perutean terjadi. Karena itu satu
target Hermes dihasilkan: BADAN byte-identik, hanya deskripsinya yang dipendekkan ke batas host.
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "skills", "samewrite", "SKILL.md")
OUT = os.path.join(ROOT, "adapters")
HEADER = ("<!-- generated by tools/adapters.py from skills/samewrite/SKILL.md — do not edit; "
          "CI fails on drift -->\n")
# Hermes truncates a skill description to 60 characters in its system prompt (measured against
# NousResearch/hermes-agent at 1ad89ac, release v2026.9.14). A description longer than that does
# not fail — it silently loses its routing tail, which is worse. So the host limit is respected
# here, mechanically, instead of shipping a description that only looks complete on disk.
HERMES_DESC_LIMIT = 60
HERMES_DESC = "Cheapest path to a correct, verified code change."

# The portable AgentSkills surface. Two facts force it to exist separately from skills/:
#   * the AgentSkills reference validator is CLOSED — an unknown top-level key is an error, and
#     `disable-model-invocation` on the Claude compatibility alias is exactly such a key;
#   * Codex silently IGNORES that key, so shipping the alias there un-hides it and charges the user
#     catalog bytes for a skill that exists only for Claude 1.0.0 upgraders.
# So the alias stays a Claude packaging detail and never leaves for a host that does not want it.
# This is packaging divergence. The body is byte-identical everywhere; behaviour does not fork.
AGENTSKILLS_DIR = "agentskills"


# One definition of "the body", used by every hash this project prints.
#
# The hash vocabulary drifted once and produced two different sha256 values for the same artifact
# in two documents: one caller hashed the whole file, another hashed a body it had normalised
# first. Both numbers were correct about something and neither said which, so a reader comparing
# them saw a divergence that did not exist. A single function ends that class of contradiction —
# an agreed definition that only lives in prose is not a definition.
#
#   FULL_FILE_SHA256 — every byte of the file, front matter included. Differs per host by design.
#   BODY_SHA256      — every byte AFTER the closing front-matter delimiter, unmodified. Must be
#                      identical on every host: that is the claim "one canonical behaviour".
CLOSE = b"\n---\n"


def body_bytes(path):
    """Bytes after the closing front-matter delimiter, verbatim. No stripping, no normalisation."""
    raw = open(path, "rb").read()
    if not raw.startswith(b"---\n"):
        raise SystemExit(f"{path}: no front matter")
    i = raw.find(CLOSE, 4)
    if i < 0:
        raise SystemExit(f"{path}: front matter is never closed")
    return raw[i + len(CLOSE):]


def hashes(path):
    """-> (FULL_FILE_SHA256, full size, BODY_SHA256, body size) for one artifact."""
    import hashlib
    raw, body = open(path, "rb").read(), body_bytes(path)
    return (hashlib.sha256(raw).hexdigest(), len(raw),
            hashlib.sha256(body).hexdigest(), len(body))


def split(text):
    """-> (front matter, body). Front matter = blok '---' pertama."""
    if not text.startswith("---\n"):
        raise SystemExit("SKILL.md tanpa front matter")
    _, fm, body = text.split("---\n", 2)
    return fm, body.lstrip("\n")


def render():
    fm, body = split(open(SRC, encoding="utf-8").read())
    return {
        # Codex / OpenCode / any AGENTS.md reader: paste or `cat >> AGENTS.md`
        "AGENTS.samewrite.md": HEADER + body,
        # Gemini CLI reads GEMINI.md; same body, host-specific filename only
        "GEMINI.samewrite.md": HEADER + body,
        # Portable AgentSkills surface: the canonical file, unchanged, in a tree that contains
        # ONLY spec-valid skills. Codex and any AgentSkills host install from here.
        f"{AGENTSKILLS_DIR}/samewrite/SKILL.md": "---\n" + fm + "---\n\n" + body,
        # Hermes Agent: a real skill directory, name == directory name, body byte-identical.
        # Only the description is host-shaped, and it is shorter than the host's own cut-off.
        # No generated-by header in a SKILL adapter's BODY. It is one comment line, but it makes
        # this host's body differ from the canonical body under any honest byte-for-byte
        # definition — and then "the body is identical everywhere" needs a footnote, which is
        # exactly the kind of almost-true claim this project refuses to ship. The do-not-edit
        # warning is already enforced mechanically by the CI drift check, which is stronger than
        # a comment anyone can ignore. Instruction-file adapters keep the header: they have no
        # frontmatter, no body/metadata split, and a human may paste them somewhere by hand.
        "hermes/samewrite/SKILL.md": (
            "---\n"
            "name: samewrite\n"
            f"description: {HERMES_DESC}\n"
            "---\n\n" + body),
    }


# Where each host's installable artifact actually lives. OpenClaw installs the canonical file
# unchanged, so it shares a row's path with Claude — and its identical hash is a fact about the
# install route, not a copy-paste.
SURFACES = [
    ("CLAUDE (canonical)", "skills/samewrite/SKILL.md"),
    ("CODEX / AGENTSKILLS", "adapters/agentskills/samewrite/SKILL.md"),
    ("HERMES", "adapters/hermes/samewrite/SKILL.md"),
    ("OPENCLAW", "skills/samewrite/SKILL.md"),
]


def report():
    """Print the cross-host hash table. Exit 1 if the bodies are not all identical."""
    rows = [(n, hashes(os.path.join(ROOT, p))) for n, p in SURFACES]
    print(f"{'artifact':22}{'FULL_FILE_SHA256':>18}{'bytes':>8}"
          f"{'BODY_SHA256':>20}{'bytes':>8}{'desc':>6}")
    for name, (fh, fn, bh, bn) in rows:
        path = dict((n, p) for n, p in SURFACES)[name]
        d = 0
        for line in open(os.path.join(ROOT, path), encoding="utf-8"):
            if line.startswith("description:"):
                d = len(line.split(":", 1)[1].strip())
                break
        print(f"{name:22}{fh[:16]:>18}{fn:>8}{bh[:16]:>20}{bn:>8}{d:>6}")
    same = len({bh for _, (_, _, bh, _) in rows}) == 1
    print("\nCROSS_HOST_BODY_IDENTITY = " + ("PASS" if same else "FAIL"))
    return 0 if same else 1


def main(argv):
    if "--hashes" in argv:
        return report()
    want = render()
    if "--check" in argv:
        bad = []
        for name, text in want.items():
            p = os.path.join(OUT, name)
            have = open(p, encoding="utf-8").read() if os.path.exists(p) else None
            if have != text:
                bad.append(name)
        if bad:
            print("DRIFT: " + ", ".join(bad) + " — jalankan tools/adapters.py")
            return 1
        print("adapters cocok dengan kanonik (%d berkas)" % len(want))
        return 0
    os.makedirs(OUT, exist_ok=True)
    for name, text in want.items():
        q = os.path.join(OUT, name)
        os.makedirs(os.path.dirname(q), exist_ok=True)
        open(q, "w", encoding="utf-8").write(text)
        print("tulis", os.path.relpath(q, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
