#!/usr/bin/env python3
"""Satu sumber kanonik, adapter yang DIHASILKAN — bukan salinan yang menyimpang diam-diam.

    python3 tools/adapters.py            # tulis ulang adapters/ dari skills/samewrite/SKILL.md
    python3 tools/adapters.py --check    # exit 1 bila adapters/ tak sama dengan hasil generate

Kanonik = skills/samewrite/SKILL.md (Claude Code memuatnya langsung). Adapter hanya mengganti
metadata di kepala; badannya byte-identik. Host lain membaca berkas Markdown instruksi
(Codex/OpenCode: AGENTS.md; Gemini CLI: GEMINI.md) — dukungan di sana INSTRUCTION_ONLY,
belum diuji perilakunya (docs/VNEXT.md §matriks dukungan).
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "skills", "samewrite", "SKILL.md")
OUT = os.path.join(ROOT, "adapters")
HEADER = ("<!-- generated by tools/adapters.py from skills/samewrite/SKILL.md — do not edit; "
          "CI fails on drift -->\n")


def split(text):
    """-> (front matter, body). Front matter = blok '---' pertama."""
    if not text.startswith("---\n"):
        raise SystemExit("SKILL.md tanpa front matter")
    _, fm, body = text.split("---\n", 2)
    return fm, body.lstrip("\n")


def render():
    fm, body = split(open(SRC, encoding="utf-8").read())
    return {
        # Codex / OpenCode / any AGENTS.md reader: paste or `cat >> AGENTS.md`
        "AGENTS.samewrite.md": HEADER + body,
        # Gemini CLI reads GEMINI.md; same body, host-specific filename only
        "GEMINI.samewrite.md": HEADER + body,
    }


def main(argv):
    want = render()
    if "--check" in argv:
        bad = []
        for name, text in want.items():
            p = os.path.join(OUT, name)
            have = open(p, encoding="utf-8").read() if os.path.exists(p) else None
            if have != text:
                bad.append(name)
        if bad:
            print("DRIFT: " + ", ".join(bad) + " — jalankan tools/adapters.py")
            return 1
        print("adapters cocok dengan kanonik (%d berkas)" % len(want))
        return 0
    os.makedirs(OUT, exist_ok=True)
    for name, text in want.items():
        open(os.path.join(OUT, name), "w", encoding="utf-8").write(text)
        print("tulis", os.path.relpath(os.path.join(OUT, name), ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
