#!/usr/bin/env python3
"""Baca ledger lapangan dan laporkan apa yang guard benar-benar lakukan.

Ledger ditulis hooks/write_noop_guard.py bila SAMEWRITE_LEDGER diset. Isinya
hanya ukuran dan hasil — tak ada path, nama berkas, atau isi. Alat ini
meringkasnya, dan dengan --markdown menghasilkan blok yang aman di-commit
(host di-hash: nama mesin bukan agregat, dan repo ini publik).

pakai: python3 tools/report.py LEDGER.jsonl [LEDGER2.jsonl ...] [--markdown] [--days N]
"""
import argparse, collections, hashlib, json, os, sys, time

EDIT_FRAC = 0.25          # aturan skill: fraksi byte berubah < 25% -> Edit lebih murah
SMALL_BLOCKS = 3          # aturan LAMA, hanya untuk ledger sebelum `frac` ada
TOK_PER_BYTE = 1 / 3.14   # dari pengukuran o200k pada korpus kode; lihat docs/FINDINGS.md


def load(paths, days=None):
    cutoff = time.time() - days * 86400 if days else 0
    for p in paths:
        if not os.path.exists(p):
            continue
        for line in open(p, errors="replace"):
            line = line.strip()
            if not line:
                continue
            try:
                r = json.loads(line)
            except Exception:
                continue
            if r.get("ts", 0) >= cutoff:
                yield r


def anon(host):
    """Nama host bukan agregat, dan FIELD_DATA.md di-commit ke repo publik."""
    return "host-" + hashlib.blake2b(host.encode(), digest_size=3).hexdigest()


def summarize(recs):
    zero = lambda: dict(checked=0, denied=0, bytes_saved=0, rewrites=0, small=0, small_bytes=0)
    s = collections.defaultdict(zero)
    days = collections.defaultdict(zero)
    for r in recs:
        h = r.get("host", "?")
        d = time.strftime("%Y-%m-%d", time.gmtime(r.get("ts", 0)))
        for bucket in (s[h], days[d]):
            if r.get("event") == "checked":
                bucket["checked"] += 1
                blk, frac = r.get("blocks"), r.get("frac")
                if r.get("same") is False and isinstance(blk, int):
                    bucket["rewrites"] += 1
                    fits = (frac < EDIT_FRAC if isinstance(frac, (int, float))
                            else blk <= SMALL_BLOCKS)   # ledger lama: tanpa frac
                    if fits:                            # muat di Edit, ditulis ulang penuh
                        bucket["small"] += 1
                        bucket["small_bytes"] += r.get("bytes", 0)
            elif r.get("event") == "denied":
                bucket["denied"] += 1
                bucket["bytes_saved"] += r.get("bytes", 0)
    return s, days


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ledgers", nargs="+")
    ap.add_argument("--markdown", action="store_true")
    ap.add_argument("--days", type=int)
    a = ap.parse_args()
    recs = list(load(a.ledgers, a.days))
    if not recs:
        print("ledger kosong — guard belum pernah berjalan, atau SAMEWRITE_LEDGER tak diset")
        return 0
    per_host, per_day = summarize(recs)
    tot_c = sum(v["checked"] for v in per_host.values())
    tot_d = sum(v["denied"] for v in per_host.values())
    tot_b = sum(v["bytes_saved"] for v in per_host.values())
    rate = 100 * tot_d / tot_c if tot_c else 0
    tot_rw = sum(v["rewrites"] for v in per_host.values())
    tot_sm = sum(v["small"] for v in per_host.values())
    tot_sb = sum(v["small_bytes"] for v in per_host.values())
    edit_line = ""
    if tot_rw:
        edit_line = (f"Rewrites that changed under {EDIT_FRAC:.0%} of the file: {tot_sm:,} of "
                     f"{tot_rw:,} ({100 * tot_sm / tot_rw:.1f}%) — {tot_sb:,} bytes "
                     f"(~{tot_sb * TOK_PER_BYTE:,.0f} tokens) resent for a change that would "
                     f"have fit in an Edit. The guard does not block these; this is a "
                     f"measurement, not a verdict.")
    if a.markdown:
        print("<!-- generated by tools/report.py — do not edit by hand -->")
        print(f"\n## Field data\n")
        print(f"Range: {min(per_day)} … {max(per_day)} ({len(per_day)} days)\n")
        print(f"| host | writes checked | denied | % | bytes saved | ~tokens |")
        print(f"|---|---|---|---|---|---|")
        for h, v in sorted(per_host.items()):
            r = 100 * v["denied"] / v["checked"] if v["checked"] else 0
            print(f"| `{anon(h)}` | {v['checked']:,} | {v['denied']:,} | {r:.1f}% | "
                  f"{v['bytes_saved']:,} | {v['bytes_saved']*TOK_PER_BYTE:,.0f} |")
        print(f"| **total** | **{tot_c:,}** | **{tot_d:,}** | **{rate:.1f}%** | "
              f"**{tot_b:,}** | **{tot_b*TOK_PER_BYTE:,.0f}** |")
        print(f"\nRetrospective over 1,316 transcripts: 20.8% (154/741). Field: "
              f"**{rate:.1f}%** of {tot_c:,} writes.")
        if edit_line:
            print(f"\n{edit_line}")
        if tot_c >= 100 and rate < 2:
            print(f"\n> **Falsifier fired.** The README says so itself: under 2% on an "
                  f"adequate sample means the finding did not generalise — remove the hook.")
    else:
        print(f"Write diperiksa {tot_c:,} · ditolak {tot_d:,} ({rate:.1f}%) · "
              f"byte diselamatkan {tot_b:,} (~{tot_b*TOK_PER_BYTE:,.0f} token)")
        for h, v in sorted(per_host.items()):
            r = 100 * v["denied"] / v["checked"] if v["checked"] else 0
            print(f"  {h:<20} periksa {v['checked']:>6,} · tolak {v['denied']:>5,} ({r:>5.1f}%)")
        if edit_line:
            print(f"  {edit_line}")
        for d in sorted(per_day)[-7:]:
            v = per_day[d]
            print(f"  {d}  periksa {v['checked']:>6,} · tolak {v['denied']:>5,}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
